package br.org.venturus.example.model.imgur

data class Imgur(
    @Transient val id: String? = null,
    @Transient val title: String? = null,
    @Transient val description: String? = null,
    @Transient val datetime: Int? = null,
    @Transient val cover: String? = null,
    @Transient val cover_width: Int? = null,
    @Transient val cover_height: Int? = null,
    @Transient val account_url: String? = null,
    @Transient val account_id: Int? = null,
    @Transient val privacy: String? = null,
    @Transient val layout: String? = null,
    @Transient val views: Int? = null,
    @Transient val link: String? = null,
    @Transient val ups: Int? = null,
    @Transient val downs: Int? = null,
    @Transient val points: Int? = null,
    @Transient val score: Int? = null,
    @Transient val is_album: Boolean? = null,
    @Transient val vote: String? = null,
    @Transient val favorite: Boolean? = null,
    @Transient val nsfw: Boolean? = null,
    @Transient val section: String? = null,
    @Transient val comment_count: Int? = null,
    @Transient val favorite_count: Int? = null,
    @Transient val topic: String? = null,
    @Transient val topic_id: String? = null,
    @Transient val images_count: Int? = null,
    @Transient val in_gallery: Boolean? = null,
    @Transient val is_ad: Boolean? = null,
    @Transient val tags: MutableList<Any>? = null,
    @Transient val ad_type: Int? = null,
    @Transient val ad_url: String? = null,
    @Transient val is_most_viral: Boolean? = null,
    @Transient val include_album_ads: Boolean? = null,
    val images: MutableList<Image> = mutableListOf(),
    @Transient val ad_config: Any? = null,
)
